version: 2
jobs:
  accept_library_licenses:
            docker:
              - image: circleci/android:api-25-alpha
            working_directory: ~/weather-app-kotlin
            environment:
              JVM_OPTS: -Xmx4G
            steps:
              - checkout
              - run: cp -r licenses/. $ANDROID_HOME/licenses
  running_test:
        docker:
          - image: circleci/android:api-25-alpha
        environment:
          JVM_OPTS: -Xmx4G
        steps:
          - checkout
          - restore_cache:
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}
          - run:
             name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
             command: sudo chmod +x ./gradlew
          - run:
             name: Install Android NDK
             command: source scripts/circleCiEnvironmentSetup.sh && getAndroidNDK
          - run:
              name: Download Dependencies
              command: ./gradlew androidDependencies
          - save_cache:
              paths:
                - ~/.gradle
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}
          - run:
              name: Run Presentation Module Unit Tests
              command: ./gradlew :presentation:testDebugUnitTest
          - store_artifacts:
              path: presentation/build/reports
          - store_test_results:
              path: presentation/build/test-results
          - run:
              name: Run Domain Module Unit Tests
              command: ./gradlew :domain:test
          - store_artifacts:
              path: domain/build/reports
          - store_test_results:
              path: domain/build/test-results
          - run:
              name: Run Data Module Unit Tests
              command: ./gradlew :data:testDebugUnitTest
          - store_artifacts:
              path: data/build/reports
          - store_test_results:
              path: data/build/test-results
          - run:
              name: Run Tests
              command: ./gradlew lint test
          - store_test_results:
                    path: presentation/build/test-results
  build_release:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}
      - run:
          name: Initial build
          command: ./gradlew clean assembleRelease --no-daemon --stacktrace
      - store_artifacts:
          path: presentation/build/outputs/apk/
          destination: apks/
workflows:
  version: 2
  test_and_build:
    jobs:
      - accept_library_licenses
      - running_test:
          requires:
            - accept_library_licenses
      - build_release:
          requires:
            - running_test
